---

- name: Load homeserver configuration
  shell: cat {{ homeserver_yaml_path }}
  register: homeserver_config

- name: Save homeserver configuration
  set_fact:
    homeserver_conf: "{{ homeserver_config.stdout | from_yaml }}"

- name: Set database type
  set_fact:
    database_engine: "{{ homeserver_conf['database']['name'] }}"

- name: Set database name
  set_fact:
    database_name: "{{ homeserver_conf['database']['args']['database'] }}"
    database_user: "{{ homeserver_conf['database']['args']['user'] }}"
    database_password: "{{ homeserver_conf['database']['args']['password'] }}"
  when: database_engine == "psycopg2"
